import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Marquee from "@/components/Marquee";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";

const notoSerifBangali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"]
})


export const metadata: Metadata = {
  title: "Bazar Dor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${notoSerifBangali.className} h-full antialiased`}
    >
      <body className=" min-h-full flex flex-col">

        <Header></Header>

        <Marquee></Marquee>

        <main>{children}</main>

        <Footer></Footer>

        <ToastContainer />

      </body>
    </html>
  );
}
